-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 20:03:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`auctions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`auctions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`auctions` (
  `auction_id` INT NOT NULL,
  `item_id` INT NULL,
  `current_offer` DOUBLE NULL,
  `bidder_id` INT NULL,
  PRIMARY KEY (`auction_id`),
  INDEX `bidder_id_idx` (`bidder_id` ASC) VISIBLE,
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `bidder_id`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`current_listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`current_listings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`current_listings` (
  `current_listings_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `item_id` INT NULL,
  PRIMARY KEY (`current_listings_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  UNIQUE INDEX `current_listings_id_UNIQUE` (`current_listings_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NULL,
  `item_description` LONGTEXT NULL,
  `auction_id` INT UNSIGNED NULL DEFAULT 0 COMMENT 'if the item is an of type auction then item will contain the forignkey to the auction',
  `starting_price` DOUBLE NULL COMMENT 'this will either be the starting price of the item or the fixed price for a standard sale\n',
  `date_listed` DATE NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sold_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sold_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sold_items` (
  `sold_item_id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NULL,
  `user_id` INT NULL,
  `date_purchased` DATE NULL,
  `date_listed` DATE NULL,
  PRIMARY KEY (`sold_item_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `email_address` VARCHAR(45) NULL,
  `home_address` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
